spring.application.name=Stock

# PostgreSQL (Supabase - \uADF8\uB300\uB85C \uC0AC\uC6A9)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.fayolygraefpyganlcpr
spring.datasource.password=gozldgkwlak12
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Redis (RedisLabs - \uADF8\uB300\uB85C \uC0AC\uC6A9)
spring.session.store-type=redis
spring.redis.host=redis-10782.c8.us-east-1-4.ec2.cloud.redislabs.com
spring.redis.port=10782
spring.redis.username=default
spring.redis.password=hnv60De9JCdr0txUlV9o1OnDfpzK8i6W

# Kafka (Docker \uCEE8\uD14C\uC774\uB108)
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=stock-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

server.port=8080