#docker bulid할떄 nginx사용시 주석 제거

version: '3'
services: 
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - stock-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - stock-network

  # docker 컨테이너로 실행할떄 사용 -> nginx에서도 수정 필요
  # user-service:
  #   build: ../StockBackEndDistributed/user-service
  #   container_name: user-service
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #     - KAFKA_BOOTSTRAP=kafka:9092
  #     - STOCK_SERVICE_URL=http://stock-service:8083
  #   depends_on:
  #     - kafka
  #   networks:
  #     - stock-network

  # stock-service:
  #   build: ../StockBackEndDistributed/stock-service
  #   container_name: stock-service
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #     - USER_SERVICE_URL=http://user-service:8082
  #   networks:
  #     - stock-network

  # order-service:
  #   build: ../StockBackEndDistributed/order-service
  #   container_name: order-service
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #     - KAFKA_BOOTSTRAP=kafka:9092
  #     - USER_SERVICE_URL=http://user-service:8082
  #     - STOCK_SERVICE_URL=http://stock-service:8083
  #   depends_on:
  #     - kafka
  #     - user-service
  #     - stock-service
  #   networks:
  #     - stock-network

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    # depends_on:
    #   - user-service
    #   - stock-service
    #   - order-service
    networks:
      - stock-network

networks:
  stock-network:
    driver: bridge